# Generated by Django 6.0.3 on 2026-03-16 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Día bloqueado')),
                ('motivo', models.CharField(blank=True, help_text='Ej. Navidad, Vacaciones, etc.', max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='horario',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la sesión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de la sesión'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HorarioDisponible',
        ),
    ]
