# Generated by Django 6.0.3 on 2026-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diafestivo_remove_cita_horario_cita_fecha_cita_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_animo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de ánimo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(default='Primera sesión', max_length=150, verbose_name='Motivo de consulta'),
        ),
    ]
