# Generated by Django 6.0.3 on 2026-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita_estado_animo_alter_cita_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='enlace_meet',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diafestivo',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
