# Generated by Django 6.0.3 on 2026-03-22 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cita_enlace_meet_alter_diafestivo_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CuestionarioRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo_elegido', models.CharField(max_length=50, verbose_name='Tipo de Terapia (Individual, Pareja, Menor)')),
                ('respuestas', models.JSONField(default=dict, verbose_name='Respuestas del Cuestionario')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_inicial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
