# Generated by Django 6.0.3 on 2026-03-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuarioperfil_usuario_cuestionarioregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Confirmada', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(max_length=50, unique=True, verbose_name='Cédula Profesional')),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20, verbose_name='Género')),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidad (Ej. Terapia Cognitiva)')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Aceptando nuevos pacientes')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_psicologo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_sesion', models.TextField(verbose_name='Notas privadas del psicólogo')),
                ('diagnostico_temporal', models.CharField(blank=True, max_length=250, null=True)),
                ('tareas_asignadas', models.TextField(blank=True, null=True, verbose_name='Tareas para el paciente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_clinica', to='core.cita', verbose_name='Cita Relacionada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_clinicos', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas', to='core.perfilpsicologo')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_agendadas', to='core.perfilpsicologo'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='psicologo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to='core.perfilpsicologo', verbose_name='Psicólogo Asignado'),
        ),
    ]
