# Generated by Django 5.2.1 on 2026-03-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cita_id_alter_cuestionarioregistro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
