"""
Django settings for hope_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-70c)rfvkj57#%*tialyzlfda=h@uqh6n#k(p$#e+mk^upfcv5k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'core',
    'rest_framework',
    'import_export',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hope_project.urls'

# 1. Configuración de Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ¡Esta línea es súper importante!
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hope_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hope',
        'USER': 'root',  # Cambia esto por tu usuario de MySQL local
        'PASSWORD': 'JBVzIRkXKqXsefqrezTQKSQSQiLokjKw',  # Cambia esto por tu contraseña
        'HOST': 'yamanote.proxy.rlwy.net',
        'PORT': '48237',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'es-mx'  # Cambiamos 'en-us' por 'es-mx' para Español México
TIME_ZONE = 'America/Mexico_City' # Pon tu zona horaria
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 2. Configuración de Archivos Estáticos (CSS, JS, Imágenes de diseño)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 3. Configuración de Archivos Multimedia (Fotos que suban los usuarios)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO (SMTP)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Cuando tengas correo empresarial, cambiarás esto (ej. smtp.hostinger.com o smtp.office365.com)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soporte.sistemas@atizapan.gob.mx'  # Pon tu Gmail actual
# OJO: Usa una "Contraseña de Aplicación" de Google, no tu contraseña normal.
EMAIL_HOST_PASSWORD = 'jhzn rzll diyt wqcx'
DEFAULT_FROM_EMAIL = 'Plataforma HOPE <soporte.sistemas@atizapan.gob.mx>'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://espaciohope.com',
    'https://www.espaciohope.com',
    'https://espaciohope.com',
    'https://www.espaciohope.com',   
    'http://localhost:8000',
    'https://espacio-hope.com',
    'https://www.espacio-hope.com',
    'https://espaciohope.info',
    'https://www.espaciohope.info',
    'https://espaciohope.mx',
    'https://www.espaciohope.mx',
    'https://espaciohope.org',
    'https://www.espaciohope.org',

]

ALLOWED_HOSTS = ['espaciohope.com', 
'www.espaciohope.com', 'localhost',
 '127.0.0.1', 'espacio-hope.com', 
 'www.espacio-hope.com',
 'espacio-hope.com',
 'www.espacio-hope.com',
 'espaciohope.info',
 'www.espaciohope.info',
 'espaciohope.mx',
 'www.espaciohope.mx',
 'espaciohope.org',
 'www.espaciohope.org',

 ]

